Update extractor_callbacks.cpp
Project-OSRM/osrm-backend pull request #5381
Opened 2019-02-28 11:30 UTC by mostafa-j13

way_id overflow with 64 bit number

# Issue

https://github.com/Project-OSRM/osrm-backend/issues/5380

2019-04-21 05:35 UTC, mostafa-j13 commented on src/extractor/extractor_callbacks.cpp
> -        {OSMWayID{static_cast<std::uint32_t>(input_way.id())},
here this must be uint64_t
 #5380

2019-04-21 05:37 UTC, mostafa-j13 commented on src/extractor/extractor_callbacks.cpp
> -        {OSMWayID{static_cast<std::uint32_t>(input_way.id())},
i fixed in #5381

2020-09-01 09:18 UTC, akashihi approved these changes

2020-09-01 09:23 UTC, akashihi requested changes
I think the issue it with 33bit node ids, not way ids?

2020-09-02 00:19 UTC, wangyoucao577 commented
> I think the issue it with 33bit node ids, not way ids?

It's indeed `way_id` overflow, not only `node_id`. But it's mostly for non-OSM data set since the biggest OSM `way_id` value is about 565140676, which fits within 2^30. See comments in https://github.com/Project-OSRM/osrm-backend/issues/5380#issuecomment-468330377

2022-08-21 21:11 UTC, SiarheiFedartsou commented
done in https://github.com/Telenav/osrm-backend/commit/6283c6074066f98e6d4a9f774f21ea45407c0d52

2022-08-21 21:11 UTC, closed without merging