Configure clang-tidy job on CI
Project-OSRM/osrm-backend pull request #6261
Opened 2022-06-16 13:39 UTC by SiarheiFedartsou

# Issue

Configures job on CI which runs clang-tidy on each pull request. Many of useful checks are disabled for the time being, because it was non-trivial to fix right in this PR, but it can be addressed later.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2022-06-16 13:40 UTC, SiarheiFedartsou commented on .github/workflows/osrm-backend.yml
> +            CLANG_VERSION: 11.0.0
`11.0.0` is chosen because it is [the latest version](https://github.com/mapbox/mason/tree/master/scripts/clang++) available in mason.

2022-06-16 13:41 UTC, SiarheiFedartsou commented on scripts/error_on_dirty.sh
> +    git diff
I use Apple Silicon mac, that's why script for formatting code doesn't work locally for me. It helped me to understand what CI wants from me to be formatted.

2022-06-17 14:22 UTC, SiarheiFedartsou commented
@mjjbell may I ask you to take a look? Tagging you as a maintainer who reviewed recent merged PRs :)

2022-06-21 21:46 UTC, mjjbell commented
> @mjjbell may I ask you to take a look? Tagging you as a maintainer who reviewed recent merged PRs :)

Thanks, I'll take a look later in the week.

2022-06-26 18:24 UTC, mjjbell commented
@SiarheiFedartsou can you include a changelog entry?

2022-06-26 18:59 UTC, mjjbell requested changes
Thanks, this is already highlighting a few code smells.

Double-check the linting comment and add a changelog entry.

2022-06-26 18:59 UTC, mjjbell commented on include/util/typedefs.hpp
> +// NOLINTNEXTLINE(bugprone-throw-keyword-missing)
Are these needed? I can omit these with clang 11.

Doesn't appear to match the [description](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-throw-keyword-missing.html) either.

2022-06-27 07:07 UTC, SiarheiFedartsou commented
Hi @mjjbell 

> Double-check the linting comment and add a changelog entry.

Is this entry in changelog not enough? 
<img width="2238" alt="Screenshot 2022-06-27 at 09 07 17" src="https://user-images.githubusercontent.com/266271/175880031-9ecba6eb-e7bb-4bc4-93ed-cb09520dc392.png">

2022-06-27 07:20 UTC, SiarheiFedartsou commented
> [Details](/Project-OSRM/osrm-backend/runs/7062551217?check_suite_focus=true)
> [ <img alt="" width="20" height="20" src="https://avatars.githubusercontent.com/oa/39145?s=40&amp;u=005fa3ae4d390a88a05654b95677e957ec7643c7&amp;v=4"> ](http://www.appveyor.com)
> ** continuous-integration/appveyor/pr ** — AppVeyor build succ

Well, I see that CI doesn't like it for some reason https://github.com/Project-OSRM/osrm-backend/runs/7062547493?check_suite_focus=true. Okay, I'll take a look.

2022-06-27 08:41 UTC, mjjbell commented
Yes, my mistake.  I saw the [error](https://github.com/Project-OSRM/osrm-backend/runs/7062547493?check_suite_focus=true) and assumed it was missing.

I believe it's complaining about the white space at the end of the line.

https://github.com/Project-OSRM/osrm-backend/blob/41dda32546399f1dc12af1de41668993de44c7dc/scripts/validate_changelog.js#L20-L21

2022-06-27 19:07 UTC, SiarheiFedartsou commented
@mjjbell I've updated PR, please take a look again.

2022-06-27 23:14 UTC, merged