Deprecate .osrm file
Project-OSRM/osrm-backend pull request #6354
Opened 2022-08-31 18:44 UTC by SiarheiFedartsou

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2022-09-01 16:08 UTC, SiarheiFedartsou commented
Some things to discuss:
1. Now in order to generate `.osrm` file user has to pass `--dump-nbg-graph` flag to `osrm-extract`. Is it a good naming? Should we may be make it default and allow to disable by CLI option? I can imagine that someone somehow relies on this file and uses `osrm-components` with it(it is really low chance IMO, but still).
2. The only place where this `.osrm` can be used is `osrm-components` tool which is as I understand purely for debug, so IMO `.osrm` feels a bit "loud" name for such kind of files. May be rename it to something?
3. We suggest to pass this `.osrm` file everywhere in the docs as if it is really used as input file(e.g. `./osrm-customize ./berlin-latest.osrm`). Actually it is just a base name. So I suggest to just remove this extension from everywhere: like `./osrm-partition ./berlin-latest`. But for backward compatibility leave the ability to work if it was passed in the old way(we may emit warning if it used this way). I can imagine that a lot of people have working pipelines with this `.osrm` in them. 

@mjjbell WDYT?

2022-09-01 16:09 UTC, SiarheiFedartsou commented on .github/workflows/osrm-backend.yml
> +          docker run $MEMORY_ARGS -t -v "${PWD}:/data" "${TAG}" osrm-components /data/berlin-latest.osrm /data/berlin-latest.geojson
Added kind of smoke test for `osrm-components`.

2022-09-01 16:09 UTC, SiarheiFedartsou commented on include/extractor/extraction_containers.hpp
> +    std::vector<NodeBasedEdge> normal_edges;
Not sure about naming here, tbh haven't tried to dive into the logic there, just made it available from outside.

2022-09-01 16:09 UTC, SiarheiFedartsou commented on include/extractor/extraction_containers.hpp
> +    std::unordered_set<NodeID> internal_barrier_nodes;
The same about naming.

2022-09-01 16:10 UTC, SiarheiFedartsou commented on include/extractor/extractor.hpp
> +    ParsedOSMData ParseOSMData(ScriptingEnvironment &scripting_environment,
IMO this `ParsedOSMData` is a bit more readable than tuple we used before.

2022-09-01 16:15 UTC, SiarheiFedartsou commented on src/extractor/extractor.cpp
> +    if (config.dump_nbg_graph)
Now we are dumping `.osrm` file only if it was explicitly requested.

2022-09-26 22:23 UTC, mjjbell requested changes

2022-09-26 22:23 UTC, mjjbell commented on include/extractor/node_based_graph_factory.hpp
> +    NodeBasedGraphFactory(ScriptingEnvironment &scripting_environment,
Above comment will need updating.

2022-09-26 22:23 UTC, mjjbell commented on README.md
> +Note that `berlin-latest` has no file extension.
Referring just to the base path feels a bit odd, but I don't really have a better suggestion. Maybe always use the OSM file as the argument?

2022-09-27 16:06 UTC, SiarheiFedartsou commented on src/extractor/node_based_graph_factory.cpp
> +    std::unordered_set<NodeID> &&barriers,
Yes, only in this case we will have it actually moved https://stackoverflow.com/questions/63105858/what-happens-when-stdmove-is-called-on-a-rvalue-reference

2022-09-27 16:12 UTC, SiarheiFedartsou commented on include/extractor/extraction_containers.hpp
> +    std::unordered_set<NodeID> internal_barrier_nodes;
Renamed to `used_barrier_nodes` as we already use `barrier_nodes` for barrier's OSM ids.

2022-09-28 14:50 UTC, SiarheiFedartsou commented on .github/workflows/osrm-backend.yml
> +          # here we check that `osrm-partition` accepts base file path with `.osrm` extension even if `.osrm` file doesn't exist
Updated it

2022-09-28 14:55 UTC, SiarheiFedartsou commented
@mjjbell can you take a look again?

And also let's discuss these questions:

> Some things to discuss:
> 
> 1. Now in order to generate `.osrm` file user has to pass `--dump-nbg-graph` flag to `osrm-extract`. Is it a good naming? Should we may be make it default and allow to disable by CLI option? I can imagine that someone somehow relies on this file and uses `osrm-components` with it(it is really low chance IMO, but still).
> 2. The only place where this `.osrm` can be used is `osrm-components` tool which is as I understand purely for debug, so IMO `.osrm` feels a bit "loud" name for such kind of files. May be rename it to something?
> 3. We suggest to pass this `.osrm` file everywhere in the docs as if it is really used as input file(e.g. `./osrm-customize ./berlin-latest.osrm`). Actually it is just a base name. So I suggest to just remove this extension from everywhere: like `./osrm-partition ./berlin-latest`. But for backward compatibility leave the ability to work if it was passed in the old way(we may emit warning if it used this way). I can imagine that a lot of people have working pipelines with this `.osrm` in them.
> 
> @mjjbell WDYT?

For 1 I doubt someone really relies on it and it is super straightforward to just pass this additional flag if it is really needed.

For 3 I now more inclined to leave this `.osrm` extension everywhere with a note that it is not a specific file anymore, but base path for all other files we need(all of them have `.osrm.*` pattern in name)

2022-09-29 19:34 UTC, mjjbell commented on src/extractor/node_based_graph_factory.cpp
> +    std::unordered_set<NodeID> &&barriers,
Oops, yes of course.

2022-09-29 19:56 UTC, mjjbell commented
>  Now in order to generate `.osrm` file user has to pass `--dump-nbg-graph` flag to `osrm-extract`. Is it a good naming? Should we may be make it default and allow to disable by CLI option? I can imagine that someone somehow relies on this file and uses `osrm-components` with it(it is really low chance IMO, but still).

>  The only place where this `.osrm` can be used is `osrm-components` tool which is as I understand purely for debug, so IMO `.osrm` feels a bit "loud" name for such kind of files. May be rename it to something?

It's the internal node-based-graph representation prior to compression, creation of dummy edges and other stuff that doesn't exist in the OSM data. So I would say it's the correct arg name, but I agree that it's not obvious that this should generate an `.osrm` file. 

Renaming it to `.nbg` seems like a good fit with the other [toolchain output](https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview), given we have already have the OSM IDs and coordinates in `.nbg_nodes`, and the compressed graph in `.cnbg`.

>  We suggest to pass this `.osrm` file everywhere in the docs as if it is really used as input file(e.g. `./osrm-customize ./berlin-latest.osrm`). Actually it is just a base name. So I suggest to just remove this extension from everywhere: like `./osrm-partition ./berlin-latest`. But for backward compatibility leave the ability to work if it was passed in the old way(we may emit warning if it used this way). I can imagine that a lot of people have working pipelines with this `.osrm` in them.

Thinking longer-term, I can see an approach where we pass around a metadata/config file, that includes information about the settings used during processing, and detailing which datasets have been generated (e.g. if we wanted to support [optional loading](https://github.com/Project-OSRM/osrm-backend/issues/5838)), which maybe could be a good use for an `.osrm` file? In which case it would be beneficial to keep the instructions for passing that as the argument. What do you think?

2022-09-29 20:04 UTC, mjjbell commented
> For 3 I now more inclined to leave this .osrm extension everywhere with a note that it is not a specific file anymore, but base path for all other files we need(all of them have .osrm.* pattern in name)

Sorry I'm reading everything in the wrong order. In that's the case, then I agree, and it also aligns with the potential of a config/metadata file in the future.

2022-09-29 20:08 UTC, mjjbell approved these changes

2022-09-29 20:08 UTC, mjjbell commented on README.md
> +Note there is no `berlin-latest.osrm` file, but multiple `berlin-latest.osrm.*` files, i.e. `berlin-latest.osrm` is not file path, but "base" path referring to set of files and there is an option to
Yep, agreed.

2022-09-29 20:08 UTC, mjjbell commented on src/extractor/extractor.cpp
> +        storage::tar::FileWriter writer(config.GetPath(".osrm").string(),
Only suggested change would be to make this `.nbg`

2022-09-29 20:15 UTC, mjjbell commented
> For 1 I doubt someone really relies on it and it is super straightforward to just pass this additional flag if it is really needed.

Agreed. Also, given the `.osrm` file is marked as temporary in the [toolchain](https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview), I don't think users can have expectations of stability.

2022-09-30 12:29 UTC, merged