Final merge commit
Project-OSRM/osrm-backend pull request #6611
Opened 2023-04-20 11:49 UTC by mugr1x

# Issue
This PR target at (partially) resolving #6551.
That is exchanging boost::optional for std::optional from C++17.
As mentioned elsewhere (https://github.com/Project-OSRM/osrm-backend/pull/6429#issuecomment-1296207761)
boost::spirit::qi does not work with std::optional, however boost::spirit::x3 does.
This PR does NOT refactor these parts of the codebase. To my knowledge there are three parsers written with ::qi (and ::phoenix) and at least the time validator and CSV parser I was abled to at least work on. (not included in this PR)
However the core API of /server alses uses ::qi and changing this would be a more peculiar if not a bad decision (for now).
Note because of failing CI this is #6593 reopened.

## Tasklist

 - [ x] CHANGELOG.md entry
 - [ x] review
 - [ x] adjust for comments
 - [ x] cherry pick to release branch

2023-08-20 14:27 UTC, mjjbell requested changes
Please rectify the `src/nodejs` changes. Otherwise, seems fine.

2023-08-20 14:27 UTC, mjjbell commented on src/nodejs/json_v8_renderer.hpp
> +#ifndef OSRM_BINDINGS_NODE_JSON_V8_RENDERER_HPP
These `src/nodejs` additions should be removed.

2023-08-20 14:27 UTC, mjjbell commented on src/guidance/intersection_handler.cpp
> +        return {};
Any particular reason why we switch between `nullopt` and `{}`?

2024-05-22 12:58 UTC, merged

2024-05-22 17:49 UTC, DennisOSRM commented
👍🏽