pass flags into process_segment
Project-OSRM/osrm-backend pull request #6658
Opened 2023-07-20 17:42 UTC by mattwigway

# Issue

This partially addresses #6145, by making the extractor edge flags available to `process_segment` as `segment.flags`. This allows accessing road classification, start point, etc. in `process_segment`. I'm using it by tagging bridges/tunnels as non-startpoints and then not applying elevation weighting to them since they are flat (ish) where I am but often cross deep valleys.

I'm not quite sure how to write an automated test for this. Maybe a profile that uses the flags information in a cucumber test?

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2023-08-20 13:20 UTC, mjjbell requested changes
> I'm not quite sure how to write an automated test for this. Maybe a profile that uses the flags information in a cucumber test?

Yes, take a look at https://github.com/Project-OSRM/osrm-backend/blob/master/features/options/extract/lua.feature and https://github.com/Project-OSRM/osrm-backend/blob/master/features/options/extract/turn_function.feature.

You could write a test that uses the flags within the profile's `process_segment` function and confirm you get the expected result.

2023-08-20 13:20 UTC, mjjbell commented on include/extractor/extraction_segment.hpp
> +                      const osrm::extractor::NodeBasedEdgeClassification flags_)
```suggestion
                      const NodeBasedEdgeClassification flags_)
```

2023-08-20 13:20 UTC, mjjbell commented on include/extractor/extraction_segment.hpp
> +    const osrm::extractor::NodeBasedEdgeClassification flags;
```suggestion
    const NodeBasedEdgeClassification flags;
```

2023-11-29 19:51 UTC, mattwigway commented
I'm having some trouble getting the Cucumber tests running to finish this, which seems to have to do the node OSRM library. It looks like it's trying to find it locally, failing, and then trying to grab it from github, which fails as well since it's a non-release version. Do I need to do something to build the Node.js bindings locally?

2023-12-12 17:13 UTC, mattwigway commented
Okay, I figured out the Cucumber tests and added a test that confirms that segment flags get passed through to `process_segment`. @mjjbell let me know if anything else is needed and my apologies for the delay.

2024-04-02 22:40 UTC, mjjbell approved these changes
LGTM. Please add a changelog entry.

2024-04-03 19:47 UTC, mattwigway commented
@mjjbell I added the changelog entry and rebased to avoid merge conflicts in changelog. Thanks!

2024-04-06 08:27 UTC, merged