support rtree preheat
Project-OSRM/osrm-backend pull request #6781
Opened 2024-02-02 08:48 UTC by hy05190134

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.
we found a lot of requests timeout when osrm is starting, but after a while the rt decrease, so we want to resolve the problem, and we found the reason is the preheat of rtree, because the leaf node of rtree is stored in the .fileIndex file and 
it use mmap so it will produce disk I/O for preheat

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2024-02-02 14:55 UTC, danpat commented
Hmm.  Why not run a simple `cat map.fileIndex > /dev/null` operation before launching `osrm-routed`?  That would have the same effect of loading all the files pages into the page cache....

2024-02-04 02:29 UTC, hy05190134 commented
> Hmm. Why not run a simple `cat map.fileIndex > /dev/null` operation before launching `osrm-routed`? That would have the same effect of loading all the files pages into the page cache....

it's right. But I just want others do not sense the process when they first use the osrm-routed and encounter the same problem when started

2024-02-04 02:33 UTC, hy05190134 commented
@danpat  another question, why the desinger of osrm just leave the .fileIndex using mmap

2024-02-04 02:49 UTC, hy05190134 commented
> Hmm. Why not run a simple `cat map.fileIndex > /dev/null` operation before launching `osrm-routed`? That would have the same effect of loading all the files pages into the page cache....

2024-07-09 17:22 UTC, DennisOSRM requested changes
the preheat is just a linear scan through the data. Seems one can do that using `cat` in any production setup.

2024-07-17 03:27 UTC, fenwuyaoji commented
@hy05190134 Hi, thanks for your work. we use your preheat method in our osrm. 
The osrm runs as a pod in k8s, and remote storage is used to save osrm data and mounted to the pod. the storage and k8s cluster are in different regions, leading to high latency, often needing to wait 10 mins until loading succeeds. 

We notice that during this init stage, the CPU usage (20m) is low but iowait (8*25%) & load (2.5) is high. I think this is due to the preheat and mmap. I'm wondering wether there is a way can solve this problem. do you have any advice?

<img width="864" alt="image" src="https://github.com/user-attachments/assets/3a127f69-c547-4275-ac1f-6662000db1a8">
![image](https://github.com/user-attachments/assets/9922e649-4140-4075-a265-8c0c3896fc0c)

2025-02-22 09:04 UTC, closed without merging